import Head from 'next/head'
import React from 'react'
import NavBar from '../NavBar'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>
        {children}
      </main>
    </>
  )
}

export default Layout